doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: 'mysql://%env(MYSQL_USERNAME)%:%env(MYSQL_PASSWORD)%@%env(MYSQL_HOST)%:%env(MYSQL_PORT)%/%env(MYSQL_DATABASE_NAME)%'
                server_version: '%env(MYSQL_SERVER_VERSION)%'
            migrations:
                url: 'mysql://%env(MYSQL_MIGRATIONS_USERNAME)%:%env(MYSQL_MIGRATIONS_PASSWORD)%@%env(MYSQL_HOST)%:%env(MYSQL_PORT)%/%env(MYSQL_DATABASE_NAME)%'
                server_version: '%env(MYSQL_SERVER_VERSION)%'

        types:
            ######################   SHARED    ######################
            name: ApiRol\Shared\Infrastructure\Persistence\Doctrine\MySQL\Type\NameType
            description: ApiRol\Shared\Infrastructure\Persistence\Doctrine\MySQL\Type\DescriptionType
            ######################    RULE     ######################
            rule_id: ApiRol\Context\Rule\Infrastructure\Write\Persistence\Doctrine\MySQL\Type\RuleIdType
            ######################  CHARACTER  ######################
            character_id: ApiRol\Context\Character\Infrastructure\Write\Persistence\Doctrine\MySQL\Type\CharacterIdType
            ability_id: ApiRol\Context\Character\Infrastructure\Write\Persistence\Doctrine\MySQL\Type\AbilityIdType
            character_ability_id: ApiRol\Context\Character\Infrastructure\Write\Persistence\Doctrine\MySQL\Type\CharacterAbilityIdType
            character_attribute: ApiRol\Context\Character\Infrastructure\Write\Persistence\Doctrine\MySQL\Type\CharacterAttributeType
            character_life: ApiRol\Context\Character\Infrastructure\Write\Persistence\Doctrine\MySQL\Type\CharacterLifeType
            character_armour: ApiRol\Context\Character\Infrastructure\Write\Persistence\Doctrine\MySQL\Type\CharacterArmourType

    orm:
        entity_managers:
            rol:
                connection: default
                validate_xml_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Rule:
                        type: xml
                        dir: '%kernel.project_dir%/src/Context/Rule/Infrastructure/Write/Persistence/Doctrine/MySQL/Mapping'
                        prefix: 'ApiRol\Context\Rule\Domain\Write'
                        is_bundle: false
                    Character:
                        type: xml
                        dir: '%kernel.project_dir%/src/Context/Character/Infrastructure/Write/Persistence/Doctrine/MySQL/Mapping'
                        prefix: 'ApiRol\Context\Character\Domain\Write'
                        is_bundle: false
