services:
  nginx-server:
    image: nginx:1.24
    container_name: rol_nginx_server
    depends_on:
      - php-fpm
    links:
      - php-fpm
    volumes:
      - ./:/var/www/rol:delegated
      - ./resources/docker/local/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8800:80"

  php-fpm:
    build: resources/docker/local/php-fpm
    container_name: rol_php_fpm
    working_dir: /var/www/rol
    volumes:
      - ./:/var/www/rol:delegated
      - /var/www/rol/var/
      - ./resources/docker/local/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

  mysql:
      container_name: rol_mysql
      image: mysql:8.0.32
      extends:
          file: resources/docker/local/mysql/volume_mappings.yml
          service: rol_mysql
      environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: rol
          MYSQL_USER: rol_user
          MYSQL_PASSWORD: rol_password
      ports:
          - '13336:3306'
