health:
    resource: '../src/Shared/UI/Symfony/routes/health.yaml'
rule:
    resource: '../src/Context/Rule/UI/Symfony/routes/rule.yaml'
character:
    resource: '../src/Context/Character/UI/Symfony/routes/character.yaml'
